fix: fee invoice name (#4900)
## Context

The `Fee#invoice_name` method was raising a `NoMethodError` when called
on credit fees with a nil `invoiceable` association. Since `invoiceable`
is optional we need to fallback to credit on this cases

## Description

Added safe navigation operator (`&.`) to the `invoiceable.name`. When
`invoiceable` is nil, the method now gracefully falls back to returning
the `fee_type` ("credit") instead of raising an error.

related to Sidekiq issue 
```
undefined method 'name' for nil (NoMethodError)
    return invoiceable.name.presence || fee_type if credit?
```