chore(queries): Refactor query filter (#4535)
As I'm [adding a filter to the
EventQuery](https://github.com/getlago/lago-api/pull/4531), I wanted to
describe a new filter validation. I realized there was a few things I
didn't like.

Filters are nested under a `filter` key, to accomodate `search_terms`
validation.

We don't do anything with search terms validation and its treated a
little differently. It's an argument to BaseQuery, just like filters.

This means we also returns errors nested under `filters` in the API
response, which is not standard. Filters are an internal thing and
should be exposed in the API. This will help with the [new error
format](https://github.com/getlago/lago-api/pull/4251) (coming on day,
but not urgent).

Example:

```http
GET /v1/customers?countries[]=INVALID
```

Before
```rb
{
    status: 422,
    error: "Unprocessable Entity",
    code: "validation_errors",
    error_details: {
        filters: {
            countries: {
                "0": [
                    "must be one of: AD, ..."
                ]
            }
        }
    }
}
```

After
```rb
{
    status: 422,
    error: "Unprocessable Entity",
    code: "validation_errors",
    error_details: {
        countries: {
            "0": [
                "must be one of: AD, ..."
            ]
        }
    }
}

```