fix(applied-coupons): Fix `GET /api/v1/applied_coupons` when coupon is deleted (#4228)
## Context

When fetching `GET /api/v1/applied_coupons`, if the related coupon was deleted, we would fail to retrieve and serialize the coupon data due to the coupon's default scope. This would result in:

```ruby
NoMethodError
undefined method 'id' for nil (NoMethodError)

        lago_coupon_id: model.coupon.id,
                                    ^^^
```

## Description

This fixes it by preloading the coupon using the `Coupon.with_discarded` scope.

I noticed while fixing that, when filtering by coupon code, we didn't take into account deleted coupons. So we could have ended up in the following situation:

```
# Context

Coupon 1 (Deleted)
Coupon 2
Applied coupon 1 (Terminated)
Applied coupon 2

# GET /api/v1/applied_coupons
[applied_coupon_2, applied_coupon_1]

# GET /api/v1/applied_coupons?coupon_code[]=applied_coupon_1&coupon_code[]=applied_coupon_2
[applied_coupon_2]
```

So I've updated the `AppliedCouponsQuery` to fix that as well.

Note that another solution would be to change `belongs_to :coupon` into `belongs_to :coupon, -> { with_discarded}` but that could have had a bigger impact.