fix(one-off-invoice): Fix create one off invoice service (#3051)
## Context

We were getting this error in
`Invoices::CreateOneOffService#tax_error?`:
```
NoMethodError undefined method `code' for an instance of BaseService::ValidationFailure (NoMethodError)
```

The reason for that is that some errors (e.g.:
`BaseService::ValidationFailure`) don't have `code`.


## Description

This PR fixes `Invoices::CreateOneOffService#tax_error?` by checking if
the actual error result responds to `code`.