fix(validation): Fixes sanitization and validation issues (#4665)
## Context

We are currently lacking some sanitizations and validations sometimes causing 500 errors:

| Description                                                                                                                                  | Error                                                                                                                                               |
| -------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------- |
| `BillableMetricController` doesn't properly sanitize the `billable_metric` parameter and fail with an exception when passing a invalid value | `undefined method 'permit' for an instance of String (NoMethodError)`                                                                               |
| `CustomerController` doesn't properly sanitize the `customer` parameter and fail with an exception when passing a invalid value              | `undefined method 'permit' for an instance of String (NoMethodError)`                                                                               |
| `Coupon`'s `reusable` attribute cannot be nil but is not validated in the model causing a PG error when passing `nil`                        | `PG::NotNullViolation: ERROR:  null value in column "reusable" of relation "coupons" violates not-null constraint (ActiveRecord::NotNullViolation)` |
| `Customer`'s `account_type` is not validated causing `ArgumentError` when passing invalid value                                              | `'partner_customer' is not a valid account_type (ArgumentError)`                                                                                    |
| `Customer`'s attributes fail when receiving strings containing null byte (`\u0000`)                                                          | `string contains null byte (ArgumentError)`                                                                                                         |
| When we receive an blank Okta `state`, we fail to retrieve the cache                                                                         | `key cannot be blank (ArgumentError)`                                                                                                               |
| When we receive an blank Okta `code`, we fail to retrieve to authenticate the user                                                           | `Error: {"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."} (LagoHttpClient::HttpError)`              |
| Login fails when either `email` or `password` contains null byte                                                                             | `string contains null byte (ArgumentError)`                                                                                                         |
| Refreshing draft invoices does not work with `one_off` invoices                                                                              | -                                                                                                                                                   |
| Wallet transactions amounts cannot be greater than `10^25`                                                                                   | `PG::NumericValueOutOfRange: ERROR:  numeric field overflow (ActiveRecord::RangeError)`                                                             |
| Wallet transactions amounts cannot be negative                                                                                               | -                                                                                                                                                   |

## Description

This fixes those sanitization/validation issues.