fix(events): update event subscription method (#1997)
## Context

Sometimes we receive `Error: NoMethodError: undefined method 'plan' for
nil` error in `Fees::CreatePayInAdvanceJob`

We need to update `subscription` method in `event` model.

## Description

If the precision of `terminated_at` is higher than seconds which are
used in condition (e.g., milliseconds), it could result in a discrepancy
where the truncated timestamp used in the condition might not match
exactly with the provided timestamp.

Based on investigation and various tests, it seems that using
`millisecond` precision solves the issue