fix(migrations): support pg databases with unaccent installed (#3048)
# Context

Support databases that have the unaccent extension installed beforehand.

## Logs

bin/rails aborted!
StandardError: An error has occurred, this and all later migrations
canceled: (StandardError)

PG::DuplicateObject: ERROR: extension "unaccent" already exists
/app/db/migrate/20220705155228_add_unaccent_extension.rb:5:in block in
up' /app/db/migrate/20220705155228_add_unaccent_extension.rb:5:in up'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateObject: ERROR: extension
"unaccent" already exists (ActiveRecord::StatementInvalid)
/app/db/migrate/20220705155228_add_unaccent_extension.rb:5:in block in
up' /app/db/migrate/20220705155228_add_unaccent_extension.rb:5:in up'

Caused by:
PG::DuplicateObject: ERROR: extension "unaccent" already exists
(PG::DuplicateObject)
/app/db/migrate/20220705155228_add_unaccent_extension.rb:5:in `block in
up'
/app/db/migrate/20220705155228
# Description

```sql
create the unaccent extension if not exist.