fix(integrations): Fix create credit note service (#4389)
## Context

There was an issue when creating credit note via integrations
aggregator:

```
NoMethodError
undefined method 'raise_if_error!' for an instance of SendWebhookJob (NoMethodError)
```

Instead of returning a result object an instance of `SendWebhookJob` was
returned.

## Description

Return result object in case the payload is not correct.