fix(alerting): Fix alert when billable_metrics is not part of the plan charges (#4841)
It's possible to create an alert for billable metric `seats` even if
there is no charge based on the `seats` billable metric.
In this case, there is no fees with this BM in the current_usage, so the
`find_value` method returns nil.

In this case, we should early return. today, we get a `NoMethodError:
undefined method '<=' for nil` error 🙄