fix(charge): Handle missing graduated_ranges (#4168)
## Context

Some error were raised by the API:

```
undefined method 'map' for nil (NoMethodError)
properties["graduated_ranges"].map(&:with_indifferent_access)
```

This happen in the `Charges::Validators::GraduatedService` when the
provided `graduated_range` argument is nil.

## Description

Ensure the arguments fallback to an empty array when missing so that the
existing validation rule on missing range can be applied.